# Generated by Django 4.0.5 on 2022-07-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('genre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.FileField(default='default.jpg', upload_to='static/images/products')),
            ],
            options={
                'verbose_name_plural': 'movies',
                'db_table': 'Movies',
            },
        ),
    ]
